baseURL = "http://example.org/"
languageCode = "en-us"
title = "Albert's Awesome Blog"
# theme = "wowchemy"
enableGitInfo = true

[pagination]
  pageSize = 10

[module]
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-modules/v5"

# Basic params required by Wowchemy; adjust later in params.toml or here
[params]
  subtitle = "My awesome journal of military equipment"
  author = "Albert Qing"
  description = "Albert's Blog"

# Example of mounting local directories (optional)
[[module.mounts]]
  source = "static"
  target = "static"

[[module.mounts]]
  source = "content"
  target = "content"

[[module.mounts]]
  source = "data"
  target = "data"

