[params]
siteTitle = "Albert's Blog"
siteTagline = "My journal of military equipment"
favicon = "media/icon.png"

# Example hero values you might reference inside Wowchemy blocks (optional helpers)
[params.hero]
headline = "Albert's Awesome Blog"
subheadline = "My journal of military equipment"
background = "images/baground.jpg"

[marketing.analytics]
google_analytics = ""

